# Generated by Django 3.2.5 on 2021-07-10 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prueba', models.CharField(max_length=9, unique=True, verbose_name='tipo_prueba')),
                ('tipo_licencia', models.CharField(max_length=2, null=True, unique=True, verbose_name='tipo_licencia')),
            ],
            options={
                'verbose_name': 'Prueba',
                'verbose_name_plural': 'Pruebas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=50, unique=True, verbose_name='ubicacionSede')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['ubicacion'],
            },
        ),
        migrations.CreateModel(
            name='tipo_identificacion',
            fields=[
                ('identificacion', models.IntegerField(primary_key=True, serialize=False, verbose_name='numId')),
                ('tipo', models.CharField(max_length=50, verbose_name='tipoId')),
            ],
            options={
                'verbose_name': 'Tipo de Identifación',
                'verbose_name_plural': 'Tipo de Identificaciones',
                'ordering': ['identificacion'],
            },
        ),
        migrations.CreateModel(
            name='persona',
            fields=[
                ('numero_identificacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.tipo_identificacion', verbose_name='numIdPersona')),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre')),
                ('primer_apellido', models.CharField(max_length=30, verbose_name='primerApellido')),
                ('segundo_apellido', models.CharField(max_length=30, verbose_name='segundoApellido')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['numero_identificacion'],
            },
        ),
        migrations.CreateModel(
            name='fecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_disponible', models.DateTimeField(unique=True)),
                ('id_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sede')),
            ],
        ),
        migrations.CreateModel(
            name='cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otras_indicaciones', models.CharField(max_length=450, null=True)),
                ('id_fecha_cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.fecha', verbose_name='fechaCita')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipo_identificacion')),
                ('id_prueba', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.prueba')),
            ],
        ),
    ]
