# Generated by Django 3.2.5 on 2021-10-04 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_curso', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Curso')),
                ('tipo_curso', models.CharField(blank=True, max_length=300, null=True, verbose_name='Tipo de Curso')),
                ('desc_curso', models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripcion de Curso')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='persona',
            fields=[
                ('numero_identificacion', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('primer_apellido', models.CharField(max_length=30, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.CharField(max_length=30, verbose_name='Segundo Apellido')),
                ('tipo_identificacion_persona', models.CharField(max_length=150, verbose_name='Tipo Identificación Persona')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=60, unique=True, verbose_name='Ubicación de la Sede')),
                ('cant_supervisores', models.IntegerField(default=0, verbose_name='Cantidad de Supervisores')),
                ('cant_computadoras', models.IntegerField(default=0, verbose_name='Cantidad de Computadoras')),
                ('activo', models.CharField(max_length=5, verbose_name='Sede Activa')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='tipo_identificacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=150, verbose_name='Tipo Identificacion')),
            ],
            options={
                'verbose_name': 'Tipo de Identifación',
                'verbose_name_plural': 'Tipo de Identificaciones',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prueba', models.CharField(max_length=50, verbose_name='Tipo de Prueba')),
                ('tipo_licencia', models.CharField(blank=True, max_length=2, null=True, verbose_name='Tipo de Licencia')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
            ],
            options={
                'verbose_name': 'Prueba',
                'verbose_name_plural': 'Pruebas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_disponible', models.DateTimeField(verbose_name='Fecha Disponible')),
                ('id_prueba', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.prueba', verbose_name='Prueba')),
                ('id_sede', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'fecha',
                'verbose_name_plural': 'fechas',
                'ordering': ['fecha_disponible'],
            },
        ),
        migrations.CreateModel(
            name='cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otras_indicaciones', models.CharField(max_length=450, null=True)),
                ('id_fecha_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fecha', verbose_name='Fecha de la Cita')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.persona')),
            ],
            options={
                'verbose_name': 'cita',
                'verbose_name_plural': 'citas',
                'ordering': ['id'],
            },
        ),
    ]
