# Generated by Django 3.2.5 on 2021-10-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='ubicacion',
            field=models.CharField(max_length=60, unique=True, verbose_name='Ubicación de la Sede'),
        ),
    ]
