# Generated by Django 3.2.5 on 2021-07-11 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sede',
            options={'ordering': ['id'], 'verbose_name': 'Sede', 'verbose_name_plural': 'Sedes'},
        ),
    ]
