# Generated by Django 3.2.5 on 2021-10-09 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fecha_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='desc_curso',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripcion del Curso'),
        ),
        migrations.AlterField(
            model_name='fecha',
            name='id_prueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prueba', verbose_name='Prueba'),
        ),
    ]
