# Generated by Django 3.2.5 on 2021-09-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cita_id_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fecha',
            name='fecha_disponible',
            field=models.DateTimeField(verbose_name='Fecha Disponible'),
        ),
    ]
