# Generated by Django 3.2.5 on 2021-07-21 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sede_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['id'], 'verbose_name': 'cita', 'verbose_name_plural': 'citas'},
        ),
        migrations.AlterModelOptions(
            name='fecha',
            options={'ordering': ['fecha_disponible'], 'verbose_name': 'fecha', 'verbose_name_plural': 'fechas'},
        ),
        migrations.AddField(
            model_name='fecha',
            name='id_prueba',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.prueba'),
            preserve_default=False,
        ),
    ]
