# Generated by Django 3.2.5 on 2021-10-09 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211009_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fecha',
            name='id_prueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.prueba', verbose_name='Prueba'),
        ),
    ]
