# Generated by Django 3.2.5 on 2021-07-21 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_fecha_id_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='fecha',
            name='id_prueba',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.prueba'),
            preserve_default=False,
        ),
    ]
