# Generated by Django 3.2.5 on 2021-07-21 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fecha_id_prueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fecha',
            name='id_prueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.prueba'),
        ),
    ]
