# Generated by Django 3.2.5 on 2021-07-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_fecha_id_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='tipo_prueba',
            field=models.CharField(max_length=9, verbose_name='tipo_prueba'),
        ),
    ]
