# Generated by Django 3.2.5 on 2021-07-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_prueba_tipo_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='activoSede'),
        ),
        migrations.AddField(
            model_name='sede',
            name='cant_computadoras',
            field=models.IntegerField(default=0, verbose_name='cantComputadoras'),
        ),
        migrations.AddField(
            model_name='sede',
            name='cant_supervisores',
            field=models.IntegerField(default=0, verbose_name='cantSupervisores'),
        ),
    ]
