# Generated by Django 3.2.5 on 2021-07-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_sede_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='activo',
            field=models.CharField(max_length=5, verbose_name='activoSede'),
        ),
    ]
