# Generated by Django 3.2.5 on 2021-07-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_prueba_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='curso',
            field=models.CharField(blank=True, max_length=90, unique=True, verbose_name='curso'),
        ),
    ]
