# Generated by Django 3.2.5 on 2021-07-29 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210729_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.curso'),
        ),
    ]
