# Generated by Django 3.2.5 on 2021-07-29 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_prueba_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='curso',
        ),
        migrations.AddField(
            model_name='curso',
            name='nomb_curso',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Curso'),
        ),
        migrations.AddField(
            model_name='prueba',
            name='id_curso',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.curso'),
        ),
    ]
