# Generated by Django 3.2.5 on 2021-07-30 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_prueba_id_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='desc_curso',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripcion de Curso'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='tipo_licencia',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='tipo_licencia'),
        ),
    ]
