# Generated by Django 3.2.5 on 2021-07-30 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210730_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='id_curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.curso'),
        ),
    ]
