# Generated by Django 3.2.5 on 2021-08-01 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_prueba_id_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='id_curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.curso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prueba',
            name='tipo_licencia',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tipo de Licencia'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='tipo_prueba',
            field=models.CharField(max_length=50, verbose_name='Tipo de Prueba'),
        ),
    ]
