# Generated by Django 3.2.5 on 2021-08-01 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210801_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='id_fecha_cita',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.fecha', verbose_name='Fecha de la Cita'),
        ),
        migrations.AlterField(
            model_name='fecha',
            name='fecha_disponible',
            field=models.DateTimeField(unique=True, verbose_name='Fecha Disponible'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='activo',
            field=models.CharField(max_length=5, verbose_name='Sede Activa'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='cant_computadoras',
            field=models.IntegerField(default=0, verbose_name='Cantidad de Computadoras'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='cant_supervisores',
            field=models.IntegerField(default=0, verbose_name='Cantidad de Supervisores'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='ubicacion',
            field=models.CharField(max_length=50, unique=True, verbose_name='Ubicación de la Sede'),
        ),
    ]
