# Generated by Django 3.2.5 on 2021-08-01 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210801_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fecha',
            name='id_prueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.prueba', verbose_name='Id de la Prueba'),
        ),
        migrations.AlterField(
            model_name='fecha',
            name='id_sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.sede', verbose_name='Id de la Sede'),
        ),
    ]
